In [3]:
import pandas as pd
csv_df = pd.read_csv('cars.csv', delimiter=";")
csv_df.head()

Car   MPG  Cylinders  Displacement  Horsepower  \
0  Chevrolet Chevelle Malibu  18.0          8         307.0       130.0   
1          Buick Skylark 320  15.0          8         350.0       165.0   
2         Plymouth Satellite  18.0          8         318.0       150.0   
3              AMC Rebel SST  16.0          8         304.0       150.0   
4                Ford Torino  17.0          8         302.0       140.0   

   Weight  Acceleration  Model Origin  
0  3504.0          12.0     70     US  
1  3693.0          11.5     70     US  
2  3436.0          11.0     70     US  
3  3433.0          12.0     70     US  
4  3449.0          10.5     70     US

In [ ]:
#principles of object oriented programming

#encapsulation - implementation details are hidden or encapsulated in objects
#inheritance - child classes can inherit from parent classes and modules
#polymorphism - objects and names exist in many forms. so, the same attribute or method can exist in multiple classes and mean different things, etc
#abstraction - handling a concept rather than the implementation details

In [4]:
#numpy basics

#this mostly covers arrays, what they are, how to manipulate them, etc

#an array is any structured list of numbers. scalars, vectors, and matrices for examples.
#scalar is one item
#vector is a set of items that has a direction
#matrix is a set that has multiple directions

In [5]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]],dtype=np.float32)
print(a.ndim, a.shape, a.dtype)

2 (2, 3) float32


In [6]:
#arrays can have any number of dimensions including zero (a scalar)
#arrays are typed: np.uint8, np.int64, np.float32, np.float64
#arrays are dense. each element of the array exists and has the same time
#arrays are faster + consume less memory than python lists
#can only combine arrays of the same shape

In [20]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], ndmin=3)
print(b)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [18]:
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]], ndmin=6)
print(b)

[[[[[[ 1  2  3]
     [ 4  5  6]]

    [[ 7  8  9]
     [10 11 12]]]]]]


In [21]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [22]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [23]:
a = a.reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
a = a.reshape(2,-1)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
a = a.ravel()
a

array([1, 2, 3, 4, 5, 6])

In [29]:
ab = np.arange(10).reshape(5,2)
ab

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [35]:
#indexing calls a value in an array from its specific location

In [36]:
#pandas has two useful data structures for small/medium data (big data makes pandas sad)
#series and dataframes
#can import data files and turn them into dataframes (csv files)